language: php
php:
- 5.5
- 5.6
- 7.0
before_script:
  - composer install
  - pecl install mongo
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- mongo mydb_test --eval 'db.addUser("travis", "test");'
services:
  - mongodb
  - redis-server
env:
  - DB=mongodb